### ISSUE TITLE
How do I use it ?

### ISSUE THREAD

**Issue by idmeneo** [TheoKouzelis/laravel-mailgun-email-validation#1]
Hi,
Your doc isn't comprehensible : how do I insert the library in my controller ? What is the method I should use ? Do you have a simple example ?
Thx for the help.

**Comment by TheoKouzelis** [comment]
Hi @idmeneo 

So just to make sure we are on the same page. This is a Laravel validation rule which extends the [Available Validation Rules](https://laravel.com/docs/5.6/validation#available-validation-rules) that are already in the framework. The validation rules can be applied in many ways all of which are [explained here](https://laravel.com/docs/5.6/validation)

But as a quick example to validate in your controller you would:
```
public function store(Request $request)
{
    $validatedData = $request->validate([
        'email' => 'required|mailgun_email:role,disposable,mailbox',
    ]);

   //do things with validated data
}
```

Let me know, or make a PR of stuff which you think would improve the readme to this package. Maybe I should just add those links to the validation docs.

**Comment by idmeneo** [comment]
Hi, Thx for your answer. I managed to make it work by simply adding the rule to the Form request.
```
public function rules()
    {
        return [
            'civilite' => 'required',
            'name' => 'required',
            'email' => 'required|max:255|unique:users|mailgun_email:mailbox'          
        ];
    }
}
```
