### ISSUE TITLE
Update for Laravel 8 and Guzzle 7 Please

### ISSUE THREAD

**Issue by r0bdiabl0** [TheoKouzelis/laravel-mailgun-email-validation#9]
Please update to use Laravel 8 and Guzzle 7 please.

**Comment by sync667** [comment]
MR #11

**Comment by gwleuverink** [comment]
It would be great if this could be tagged 👍

**Comment by TheoKouzelis** [comment]
Thanks @sync667 for the PR.

@gwleuverink here is the tag https://github.com/TheoKouzelis/laravel-mailgun-email-validation/releases/tag/1.2.0
